#!/usr/bin/env bash
# deploy/autostart.sh — Autostart management reference library for ai-agent-collector
#
# Provides autostart_install / autostart_remove / autostart_status functions
# for macOS (launchd) and Linux (systemd user units).
#
# The canonical copy of these functions is embedded in the `aac` CLI script
# generated by aac-installer.sh. This file serves as a standalone reference
# and can be sourced for testing or debugging:
#
#   source deploy/autostart.sh
#   autostart_status

set -euo pipefail

# --- Constants ---
_AAC_SERVICE_LABEL="com.ai-agent-collector"
_AAC_LAUNCHD_PLIST="$HOME/Library/LaunchAgents/${_AAC_SERVICE_LABEL}.plist"
_AAC_SYSTEMD_UNIT="ai-agent-collector.service"
_AAC_SYSTEMD_UNIT_DIR="$HOME/.config/systemd/user"
_AAC_SYSTEMD_UNIT_PATH="${_AAC_SYSTEMD_UNIT_DIR}/${_AAC_SYSTEMD_UNIT}"

# Overridable paths
AAC_BIN="${AAC_BIN:-$HOME/.local/bin/aac}"
AAC_DATA_DIR="${AAC_DATA_DIR:-$HOME/.ai-agent-collector}"
AAC_CONFIG_FILE="${AAC_CONFIG_FILE:-$AAC_DATA_DIR/config.json}"
AAC_LOG_FILE="${AAC_LOG_FILE:-$AAC_DATA_DIR/logs/aac-service.log}"

# ============================================================
# Internal helpers
# ============================================================

_detect_init_system() {
    case "$(uname -s)" in
        Darwin) echo "launchd" ;;
        Linux)
            if command -v systemctl &>/dev/null && systemctl --user status &>/dev/null 2>&1; then
                echo "systemd"
            else
                echo "none"
            fi
            ;;
        *) echo "none" ;;
    esac
}

_write_launchd_plist() {
    mkdir -p "$(dirname "$_AAC_LAUNCHD_PLIST")"
    mkdir -p "$(dirname "$AAC_LOG_FILE")"
    cat > "$_AAC_LAUNCHD_PLIST" << PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${_AAC_SERVICE_LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${AAC_BIN}</string>
        <string>run</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>StandardOutPath</key>
    <string>${AAC_LOG_FILE}</string>
    <key>StandardErrorPath</key>
    <string>${AAC_LOG_FILE}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>AGENT_DATA_COLLECTION_CONFIG</key>
        <string>${AAC_CONFIG_FILE}</string>
    </dict>
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
PLISTEOF
}

_write_systemd_unit() {
    mkdir -p "$_AAC_SYSTEMD_UNIT_DIR"
    mkdir -p "$(dirname "$AAC_LOG_FILE")"
    cat > "$_AAC_SYSTEMD_UNIT_PATH" << UNITEOF
[Unit]
Description=AI Agent Collector
After=default.target

[Service]
Type=simple
ExecStart=${AAC_BIN} run
Restart=on-failure
RestartSec=10
Environment=AGENT_DATA_COLLECTION_CONFIG=${AAC_CONFIG_FILE}

[Install]
WantedBy=default.target
UNITEOF
}

# ============================================================
# Public API
# ============================================================

autostart_install() {
    local init_system
    init_system=$(_detect_init_system)

    case "$init_system" in
        launchd)
            launchctl unload -w "$_AAC_LAUNCHD_PLIST" 2>/dev/null || true
            _write_launchd_plist
            launchctl load -w "$_AAC_LAUNCHD_PLIST"
            echo "✅ Autostart enabled (launchd)"
            echo "   Plist: $_AAC_LAUNCHD_PLIST"
            ;;
        systemd)
            _write_systemd_unit
            systemctl --user daemon-reload
            systemctl --user enable --now "$_AAC_SYSTEMD_UNIT"
            echo "✅ Autostart enabled and service started (systemd user unit)"
            echo "   Unit: $_AAC_SYSTEMD_UNIT_PATH"
            if command -v loginctl &>/dev/null; then
                if loginctl enable-linger "$(whoami)" 2>/dev/null; then
                    echo "   Linger enabled (service starts at boot without login)"
                else
                    echo "   ⚠️  Could not enable linger (service only runs while logged in)"
                fi
            fi
            ;;
        *)
            echo "⚠️  No supported init system detected (need launchd or systemd)"
            echo "   Service will run via nohup but won't auto-start on boot"
            return 1
            ;;
    esac
}

autostart_remove() {
    local init_system
    init_system=$(_detect_init_system)

    case "$init_system" in
        launchd)
            launchctl unload -w "$_AAC_LAUNCHD_PLIST" 2>/dev/null || true
            rm -f "$_AAC_LAUNCHD_PLIST"
            echo "✅ Autostart disabled (launchd plist removed)"
            ;;
        systemd)
            systemctl --user disable --now "$_AAC_SYSTEMD_UNIT" 2>/dev/null || true
            rm -f "$_AAC_SYSTEMD_UNIT_PATH"
            systemctl --user daemon-reload 2>/dev/null || true
            echo "✅ Autostart disabled (systemd unit removed)"
            ;;
        *)
            echo "No autostart configuration found"
            ;;
    esac
}

autostart_status() {
    local init_system
    init_system=$(_detect_init_system)

    case "$init_system" in
        launchd)
            if [ -f "$_AAC_LAUNCHD_PLIST" ]; then
                if launchctl list 2>/dev/null | grep -q "$_AAC_SERVICE_LABEL"; then
                    echo "✅ Autostart: enabled (launchd, loaded)"
                else
                    echo "⚠️  Autostart: plist exists but not loaded"
                    echo "   Run: aac autostart enable"
                fi
                echo "   Plist: $_AAC_LAUNCHD_PLIST"
            else
                echo "⚪ Autostart: not configured"
            fi
            ;;
        systemd)
            if [ -f "$_AAC_SYSTEMD_UNIT_PATH" ]; then
                if systemctl --user is-enabled "$_AAC_SYSTEMD_UNIT" &>/dev/null; then
                    echo "✅ Autostart: enabled (systemd)"
                else
                    echo "⚠️  Autostart: unit exists but not enabled"
                    echo "   Run: aac autostart enable"
                fi
                echo "   Unit: $_AAC_SYSTEMD_UNIT_PATH"
            else
                echo "⚪ Autostart: not configured"
            fi
            ;;
        *)
            echo "⚪ Autostart: not available (no supported init system)"
            ;;
    esac
}
