import { describe, expect, it } from 'vitest';
import {
  buildLlmBoundaries,
  buildEventsFromBoundaries,
  splitContentEventsIntoTurns,
} from '../../../assets/hooks/qoder-hook-processor.mjs';

// Qoder CLI writes slash-command plumbing as type=user rows. Only the caveat and
// the stdout row carry isMeta; the command echo itself does not, so it used to
// start a bogus turn that produced an LLM-less trace skeleton.
function userRow(text, extra = {}) {
  return {
    type: 'user',
    userType: 'external',
    entrypoint: 'cli',
    timestamp: '2026-08-27T06:50:52.808Z',
    message: { role: 'user', content: text },
    ...extra,
  };
}

const caveatRow = () => userRow(
  '<local-command-caveat>Caveat: The messages below were generated by the user '
  + 'while running local commands. DO NOT respond to these messages or otherwise '
  + 'consider them in your response unless the user explicitly asks you to.'
  + '</local-command-caveat>',
  { isMeta: true },
);
const commandRow = () => userRow('<command-message>model</command-message>\n<command-name>/model</command-name>');
const stdoutRow = () => userRow('<local-command-stdout>Model set to Ultimate (persisted)</local-command-stdout>', { isMeta: true });

const promptRow = (text, ts = '2026-08-27T06:50:56.000Z') => userRow(text, {
  promptId: '21c3d055-6800-48b0-a892-c40386abc77c',
  timestamp: ts,
});

function assistantRow(text, ts = '2026-08-27T06:50:57.000Z') {
  return {
    type: 'assistant',
    timestamp: ts,
    message: {
      role: 'assistant',
      model: 'auto',
      stop_reason: 'end_turn',
      content: [{ type: 'text', text }],
    },
  };
}

function toolResultRow(toolUseId, ts = '2026-08-27T06:50:58.000Z') {
  return userRow([{ type: 'tool_result', tool_use_id: toolUseId, content: 'ok' }], { timestamp: ts });
}

const progress = [
  { hookEvent: 'UserPromptSubmit', ts: '2026-08-27T06:50:56.000Z' },
  { hookEvent: 'Stop', ts: '2026-08-27T06:51:00.000Z' },
];

function partsOf(record) {
  return (record?.['gen_ai.input.messages_delta']?.[0]?.parts || []).map(p => String(p.content ?? ''));
}

describe('qoder slash-command control rows', () => {
  it('drops the whole /model control trio instead of opening a turn for it', () => {
    const prompt = promptRow('杭州天气');
    const assistant = assistantRow('杭州今天多云。');
    const turns = splitContentEventsIntoTurns([
      caveatRow(), commandRow(), stdoutRow(), prompt, assistant,
    ]);

    expect(turns).toHaveLength(1);
    expect(turns[0]).toEqual([prompt, assistant]);
  });

  it('keeps control text out of a preceding real turn input', () => {
    const prompt = promptRow('您好');
    const assistant = assistantRow('您好！我是 Qoder。');
    // The caveat row trails the finished turn, so it used to be appended to it.
    const turns = splitContentEventsIntoTurns([prompt, assistant, caveatRow()]);

    expect(turns).toHaveLength(1);
    const records = buildEventsFromBoundaries(
      buildLlmBoundaries(progress, turns[0]),
      turns[0],
      turns[0],
      'turn-no-leak',
      'session-1',
      'qoder',
      {},
      '/tmp/cwd',
    );

    const entry = records.find(r => r['event.name'] === 'other');
    const request = records.find(r => r['event.name'] === 'llm.request');
    expect(partsOf(entry)).toEqual(['您好']);
    expect(partsOf(request)).toEqual(['您好']);
    for (const record of records) {
      for (const part of partsOf(record)) {
        expect(part).not.toContain('local-command-caveat');
      }
    }
  });

  it('emits no records at all when a segment holds only control rows', () => {
    const turns = splitContentEventsIntoTurns([caveatRow(), commandRow(), stdoutRow()]);
    expect(turns).toEqual([]);
  });

  it('keeps an isMeta image marker on its prompt', () => {
    // Multimodal collection relies on these rows; only command envelopes go away.
    const prompt = promptRow('看这张图');
    const imageMeta = userRow([{ type: 'text', text: '[Image: source: /tmp/clip.png]' }], { isMeta: true });
    const assistant = assistantRow('图里是一只猫。');
    const turns = splitContentEventsIntoTurns([prompt, imageMeta, assistant]);

    expect(turns).toHaveLength(1);
    expect(turns[0]).toContain(imageMeta);
  });

  it('still yields one turn for a real prompt that got no model activity', () => {
    // Interrupted turns carry no assistant row and must survive the filter.
    const prompt = promptRow('帮我改一下');
    const turns = splitContentEventsIntoTurns([prompt]);

    expect(turns).toHaveLength(1);
    expect(turns[0]).toEqual([prompt]);
  });

  it('leaves tool_result rows attached to their prompt', () => {
    const prompt = promptRow('跑一下测试');
    const assistant = assistantRow('我来跑测试。');
    const result = toolResultRow('toolu_1');
    const turns = splitContentEventsIntoTurns([prompt, assistant, result]);

    expect(turns).toHaveLength(1);
    expect(turns[0]).toEqual([prompt, assistant, result]);
  });
});
